name: lighthouse_
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  custom_qr_generator: ^0.1.2
  dartz: ^0.10.1
  dio: ^5.7.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_slidable: ^3.1.1
  get_it: ^8.0.1
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.3.2
  easy_localization: 3.0.7
  flutter_svg: ^2.0.10+1

dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/svg/
